"""Synthetic multi-asset universes for the Alpha Research Engine (Phase 5, Sections 4, 6, 14).

Data-availability disclosure (Phase 5, Section 4 — carried forward from
Phase 3/4): this sandbox has no outbound network access to Binance,
CoinGecko, or any other real market-data source (every attempt returns a
proxy-level 403), and no historical OHLCV files exist anywhere in this
repository. Every quantitative result in
``docs/PHASE5_ALPHA_RESEARCH_REPORT.md`` is therefore computed on
disclosed, synthetic-but-controlled data generated by this module —
**never** presented as evidence about real crypto markets, only as
evidence about whether the *research pipeline itself* can find and
correctly validate a signal when one exists (or correctly fail to find
one when it does not). A "realistic" universe below means "constructed
to have the statistical texture believed to resemble real markets
(volatility clustering, regime shifts, weak/ambiguous autocorrelation)",
not "measured from real markets."

Survivorship-bias handling: real crypto history includes delisted/failed
assets this sandbox cannot reconstruct (no listing/delisting registry is
reachable). What CAN be honestly modeled and IS modeled here is the
*mechanical* half of the problem: assets that list partway through the
sample window. Every universe stakes out a handful of assets with a
staggered "listing start" (all-NaN OHLCV before their listing candle,
on a DatetimeIndex shared with every other asset) — this exercises and
proves (see ``tests/test_research_walk_forward.py``) that
``build_signal_panel`` never scores, ranks, or includes an asset before
its own listing point. It does NOT simulate delisting/failure, and does
NOT correct for the selection bias of "the assets in this universe are
exactly the ones that didn't fail" — that half of survivorship bias is
unavailable to correct in this sandbox and is reported as a limitation,
not silently assumed away.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

N_CANDLES = 8000  # hourly candles, ~333 days
FREQ = "h"
START = "2023-01-01"

ALT_SYMBOLS = [f"ALT{i:02d}" for i in range(1, 19)]  # 18 altcoins
ALL_SYMBOLS = ["BTC", "ETH"] + ALT_SYMBOLS  # 20 assets total
BENCHMARK_SYMBOL = "BTC"
SECOND_BENCHMARK_SYMBOL = "ETH"

# (symbol, listing_start_candle) for assets that "list" partway through
# the sample instead of being present from candle 0 -- exercises the
# no-future-listing guarantee. Everything not listed here starts at 0.
STAGGERED_LISTINGS: dict[str, int] = {
    "ALT16": 1_500,
    "ALT17": 3_200,
    "ALT18": 5_000,
}


def _dates(n: int = N_CANDLES) -> pd.DatetimeIndex:
    return pd.date_range(START, periods=n, freq=FREQ)


def _ar1(n: int, rng: np.random.Generator, phi: float, sigma: float) -> np.ndarray:
    """Zero-mean AR(1) process: x[t] = phi * x[t-1] + eps[t]."""
    eps = rng.normal(0.0, sigma, n)
    x = np.zeros(n)
    for t in range(1, n):
        x[t] = phi * x[t - 1] + eps[t]
    return x


def _ohlcv_from_close(close: pd.Series, volume: pd.Series, listing_start: int = 0) -> pd.DataFrame:
    df = pd.DataFrame(
        {
            "open": close * 0.999,
            "high": close * 1.01,
            "low": close * 0.99,
            "close": close,
            "volume": volume,
        },
        index=close.index,
    )
    if listing_start > 0:
        df.iloc[:listing_start] = np.nan
    return df


def _base_volume(n: int, rng: np.random.Generator, level: float, ret: np.ndarray) -> pd.Series:
    """Volume with a mild, realistic tie to |return| (higher-volume candles on bigger moves)."""
    noise = rng.lognormal(mean=0.0, sigma=0.35, size=n)
    scaled = level * noise * (1.0 + 3.0 * np.abs(ret))
    return pd.Series(scaled, index=_dates(n))


@dataclass(frozen=True)
class Universe:
    name: str
    description: str
    candidates: dict[str, pd.DataFrame]
    benchmark_symbol: str = BENCHMARK_SYMBOL
    second_benchmark_symbol: str = SECOND_BENCHMARK_SYMBOL


def build_positive_control_universe(seed: int = 101) -> Universe:
    """Planted alpha: each asset's realized return is driven by an observable, persistent trend.

    ``trend[t-1]`` (known at the start of candle t) linearly drives
    ``return[t]`` with a signal-to-noise ratio deliberately large enough
    to be unambiguous (mirrors Phase 3/4's positive controls) — this is
    what "momentum" (built from realized past returns) should be able to
    detect if the whole pipeline (signal -> panel -> IC -> quantiles ->
    permutation test) works at all.
    """
    rng = np.random.default_rng(seed)
    n = N_CANDLES
    dates = _dates(n)
    candidates: dict[str, pd.DataFrame] = {}

    for symbol in ALL_SYMBOLS:
        trend = _ar1(n, rng, phi=0.995, sigma=0.0015)  # slow, highly persistent drift
        noise = rng.normal(0.0, 0.006, n)
        ret = np.empty(n)
        ret[0] = 0.0
        ret[1:] = 4.0 * trend[:-1] + noise[1:]  # large trend-to-noise ratio: deliberate strong signal
        base_price = 40_000.0 if symbol == "BTC" else (2_500.0 if symbol == "ETH" else 5.0)
        close = pd.Series(base_price * np.cumprod(1 + ret), index=dates)
        volume = _base_volume(n, rng, level=(5e7 if symbol in ("BTC", "ETH") else 2e6), ret=ret)
        listing_start = STAGGERED_LISTINGS.get(symbol, 0)
        candidates[symbol] = _ohlcv_from_close(close, volume, listing_start)

    return Universe(
        name="positive_control",
        description="Planted alpha: return[t] driven 4x by an observable, persistent trend[t-1].",
        candidates=candidates,
    )


def build_null_universe(seed: int = 202) -> Universe:
    """Pure noise: iid returns, no autocorrelation, no relation to any feature. IC must be ~0 everywhere."""
    rng = np.random.default_rng(seed)
    n = N_CANDLES
    dates = _dates(n)
    candidates: dict[str, pd.DataFrame] = {}

    for symbol in ALL_SYMBOLS:
        ret = rng.normal(0.0, 0.02, n)
        ret[0] = 0.0
        base_price = 40_000.0 if symbol == "BTC" else (2_500.0 if symbol == "ETH" else 5.0)
        close = pd.Series(base_price * np.cumprod(1 + ret), index=dates)
        volume = _base_volume(n, rng, level=(5e7 if symbol in ("BTC", "ETH") else 2e6), ret=ret)
        listing_start = STAGGERED_LISTINGS.get(symbol, 0)
        candidates[symbol] = _ohlcv_from_close(close, volume, listing_start)

    return Universe(
        name="null",
        description="Pure iid Gaussian returns; no planted relationship of any kind.",
        candidates=candidates,
    )


_REGIME_SEQUENCE = ["bull", "high_vol", "sideways", "bear", "low_vol", "sideways", "bull", "high_vol"]


def build_realistic_universe(seed: int = 303) -> Universe:
    """Multi-regime synthetic market with a small, realistic-strength weak signal.

    Volatility clustering (regime-dependent sigma) plus a *weak* AR(1)
    return autocorrelation (phi ~ 0.03-0.07, an order of magnitude below
    the positive control's persistence) -- disclosed as "designed to sit
    near the edge of detectability", not measured from any real market.
    Each asset gets its own random phi/regime-volatility draw so the
    universe is not one signal repeated 20 times.
    """
    rng = np.random.default_rng(seed)
    n = N_CANDLES
    dates = _dates(n)
    segment_len = n // len(_REGIME_SEQUENCE) + 1
    regimes: list[str] = []
    for r in _REGIME_SEQUENCE:
        regimes += [r] * segment_len
    regimes = regimes[:n]

    regime_drift = {"bull": 0.0006, "bear": -0.0006, "sideways": 0.0, "high_vol": 0.0, "low_vol": 0.0001}
    regime_vol = {"bull": 0.018, "bear": 0.022, "sideways": 0.012, "high_vol": 0.045, "low_vol": 0.006}

    drift = np.array([regime_drift[r] for r in regimes])
    sigma = np.array([regime_vol[r] for r in regimes])

    candidates: dict[str, pd.DataFrame] = {}
    for symbol in ALL_SYMBOLS:
        asset_rng = np.random.default_rng(rng.integers(0, 2**32 - 1))
        phi = asset_rng.uniform(0.03, 0.07) * asset_rng.choice([-1, 1])  # sign varies: some assets weakly trend, some weakly mean-revert
        weak_trend = _ar1(n, asset_rng, phi=phi, sigma=1.0)
        weak_trend = weak_trend / (weak_trend.std() + 1e-9) * sigma.mean() * 0.15  # small, bounded contribution

        idio_noise = asset_rng.normal(0.0, 1.0, n) * sigma
        ret = drift + 0.3 * idio_noise  # regime drift + idiosyncratic vol-clustered noise
        ret[1:] += weak_trend[:-1]  # weak persistence, contemporaneous with idio noise
        ret[0] = 0.0

        base_price = 40_000.0 if symbol == "BTC" else (2_500.0 if symbol == "ETH" else 5.0)
        close = pd.Series(base_price * np.cumprod(1 + ret), index=dates)
        volume = _base_volume(n, asset_rng, level=(5e7 if symbol in ("BTC", "ETH") else 2e6), ret=ret)
        listing_start = STAGGERED_LISTINGS.get(symbol, 0)
        candidates[symbol] = _ohlcv_from_close(close, volume, listing_start)

    universe = Universe(
        name="realistic",
        description=(
            "Multi-regime (bull/bear/sideways/high_vol/low_vol) synthetic market with a weak, "
            "per-asset AR(1) return autocorrelation (|phi| in [0.03, 0.07]) layered on regime-"
            "dependent drift and volatility. Not fit to or measured from real data."
        ),
        candidates=candidates,
    )
    object.__setattr__(universe, "regime_labels", regimes)  # type: ignore[attr-defined]
    return universe
